import type { Metadata, Viewport } from "next";
import Link from "next/link";
import { auth } from "@/auth";
import { logout } from "@/server/actions";
import "./globals.css";
import ServiceWorkerRegistration from "@/components/ServiceWorkerRegistration";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: { default: "Bénévo+", template: "%s · Bénévo+" }, description: "Bénévo+ relie les personnes qui ont besoin d'un coup de main et les bénévoles.", manifest: "/manifest.webmanifest", applicationName: "Bénévo+", appleWebApp: { capable: true, title: "Bénévo+", statusBarStyle: "default" }, icons: { icon: "/icon.svg", apple: "/icon.svg" } };
export const viewport: Viewport = { themeColor: "#14213d", width: "device-width", initialScale: 1 };

function initials(name?: string | null) { return (name || "B").split(/\s+/).map(x => x[0]).join("").slice(0, 2).toUpperCase(); }
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth(); const user = session?.user;
  return <html lang="fr"><body className="flex min-h-dvh flex-col antialiased"><ServiceWorkerRegistration /><header className="sticky top-0 z-20 bg-[#14213d] text-white"><nav className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3"><Link href={user ? "/app" : "/"} className="text-xl font-bold">Bénévo<span className="text-[#c9a227]">+</span></Link>{user ? <details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2"><span className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-full bg-[#c9a227] font-bold text-[#14213d]">{user.image ? <img src={user.image} alt="" className="h-full w-full object-cover" /> : initials(user.name)}</span><span className="hidden text-sm sm:inline">{user.name || "Mon compte"}</span></summary><div className="absolute right-0 mt-2 w-52 rounded-xl bg-white p-2 text-sm text-[#14213d] shadow-xl"><Link className="block rounded-lg px-3 py-2 hover:bg-black/5" href="/app/profil">Mon profil</Link><Link className="block rounded-lg px-3 py-2 hover:bg-black/5" href="/app/communautes">Mes communautés</Link><Link className="block rounded-lg px-3 py-2 hover:bg-black/5" href="/app/profil#parametres">Paramètres</Link><form action={logout}><button className="w-full rounded-lg px-3 py-2 text-left hover:bg-black/5">Se déconnecter</button></form></div></details> : <Link href="/connexion" className="text-sm underline-offset-4 hover:underline">Se connecter</Link>}</nav></header><main className="mx-auto w-full max-w-5xl flex-1 px-4 py-6">{children}</main><footer className="border-t border-black/10 py-6 text-center text-xs text-black/60"><div className="flex flex-wrap justify-center gap-4"><Link href="/mentions-legales">Mentions légales</Link><Link href="/cgu">CGU</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/cookies">Cookies</Link></div><p className="mt-2">© {new Date().getFullYear()} Bénévo+ · édité par Ioleto</p></footer></body></html> }
